<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Hello_Agent_tutorial</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="HelloAgent.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="protos\agent_events.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoGen.Gemini" Version="0.2.3" />
    <PackageReference Include="AutoGen.OpenAI" Version="0.2.3" />
    <PackageReference Include="Microsoft.AutoGen.Contracts" Version="0.4.0-dev.3" />
    <PackageReference Include="Microsoft.AutoGen.Core" Version="0.4.0-dev.3" />
    <PackageReference Include="Microsoft.AutoGen.Core.Grpc" Version="0.4.0-dev.3" />
    <PackageReference Include="System.Speech" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="protos\" />
  </ItemGroup>

</Project>
